getenv = true 
universe = vanilla
executable = bayesprot_Rsetup.sh
log = bayesprot_Rsetup.log
error = bayesprot_Rsetup.err
output = bayesprot_Rsetup.out
should_transfer_files = YES
transfer_input_files = bayesprot_Rsetup.R
periodic_release = True
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)
priority = 10
rank = kflops
request_memory = 1500 
request_disk = 350000
requirements = (opsys == "LINUX") && (arch == "X86_64")
queue
