getenv = true 
universe = vanilla
executable = norm.R
arguments = HTCondor $(Cluster) $(Process)
initialdir = norm
log = condor.log
error = $(Process).err
output = $(Process).out
should_transfer_files = YES
transfer_input_files = ../plots.R, ../input/parameters.Rdata, ../import/$(Process).Rdata, ../build/build.zip
when_to_transfer_output = ON_EXIT
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)
rank = kflops
