getenv = true 
universe = vanilla
executable = ../bayestraq_R.sh
initialdir = plots/results
log = ../$(Process).log
output = ../$(Process).out
error = ../$(Process).err
stream_error = True
stream_output = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = stats, conditions, conditions_sd, samples, peptides_sd
periodic_release = True
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)
priority = 4
rank = kflops
