setGeneric("run", function(object, ...) standardGeneric("run"))
setGeneric("prepare", function(object, ...) standardGeneric("prepare"))
setGeneric("fits", function(object, ...) standardGeneric("fits"))
setGeneric("del", function(object, ...) standardGeneric("del"))
setGeneric("control", function(object, ...) standardGeneric("control"))
setGeneric("assay_design", function(object, ...) standardGeneric("assay_design"))
setGeneric("read_mcmc", function(object, ...) standardGeneric("read_mcmc"))
setGeneric("measurements", function(object, ...) standardGeneric("measurements"))
setGeneric("components", function(object, ...) standardGeneric("components"))
setGeneric("groups", function(object, ...) standardGeneric("groups"))
setGeneric("summary", function(object, ...) standardGeneric("summary"))
setGeneric("timings", function(object, ...) standardGeneric("timings"))
setGeneric("measurement_vars", function(object, ...) standardGeneric("measurement_vars"))
setGeneric("component_vars", function(object, ...) standardGeneric("component_vars"))
setGeneric("component_deviations", function(object, ...) standardGeneric("component_deviations"))
setGeneric("assay_deviations", function(object, ...) standardGeneric("assay_deviations"))
setGeneric("unnormalised_group_quants", function(object, ...) standardGeneric("unnormalised_group_quants"))
setGeneric("process0", function(object, ...) standardGeneric("process0"))
setGeneric("process1", function(object, ...) standardGeneric("process1"))
setGeneric("plots", function(object, ...) standardGeneric("plots"))
setGeneric("model", function(object, ...) standardGeneric("model"))


